/*
 * This file is generated by jOOQ.
 */
package dev.ku01.shop.db.pg_catalog.tables.records;


import dev.ku01.shop.db.pg_catalog.tables.PgAuthMembers;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgAuthMembersRecord extends UpdatableRecordImpl<PgAuthMembersRecord> implements Record7<Long, Long, Long, Long, Boolean, Boolean, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pg_catalog.pg_auth_members.oid</code>.
     */
    public void setOid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_auth_members.oid</code>.
     */
    public Long getOid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_auth_members.roleid</code>.
     */
    public void setRoleid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_auth_members.roleid</code>.
     */
    public Long getRoleid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_auth_members.member</code>.
     */
    public void setMember(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_auth_members.member</code>.
     */
    public Long getMember() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_auth_members.grantor</code>.
     */
    public void setGrantor(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_auth_members.grantor</code>.
     */
    public Long getGrantor() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_auth_members.admin_option</code>.
     */
    public void setAdminOption(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_auth_members.admin_option</code>.
     */
    public Boolean getAdminOption() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_auth_members.inherit_option</code>.
     */
    public void setInheritOption(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_auth_members.inherit_option</code>.
     */
    public Boolean getInheritOption() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>pg_catalog.pg_auth_members.set_option</code>.
     */
    public void setSetOption(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_auth_members.set_option</code>.
     */
    public Boolean getSetOption() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, Long, Long, Boolean, Boolean, Boolean> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, Long, Long, Boolean, Boolean, Boolean> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return PgAuthMembers.PG_AUTH_MEMBERS.OID;
    }

    @Override
    public Field<Long> field2() {
        return PgAuthMembers.PG_AUTH_MEMBERS.ROLEID;
    }

    @Override
    public Field<Long> field3() {
        return PgAuthMembers.PG_AUTH_MEMBERS.MEMBER;
    }

    @Override
    public Field<Long> field4() {
        return PgAuthMembers.PG_AUTH_MEMBERS.GRANTOR;
    }

    @Override
    public Field<Boolean> field5() {
        return PgAuthMembers.PG_AUTH_MEMBERS.ADMIN_OPTION;
    }

    @Override
    public Field<Boolean> field6() {
        return PgAuthMembers.PG_AUTH_MEMBERS.INHERIT_OPTION;
    }

    @Override
    public Field<Boolean> field7() {
        return PgAuthMembers.PG_AUTH_MEMBERS.SET_OPTION;
    }

    @Override
    public Long component1() {
        return getOid();
    }

    @Override
    public Long component2() {
        return getRoleid();
    }

    @Override
    public Long component3() {
        return getMember();
    }

    @Override
    public Long component4() {
        return getGrantor();
    }

    @Override
    public Boolean component5() {
        return getAdminOption();
    }

    @Override
    public Boolean component6() {
        return getInheritOption();
    }

    @Override
    public Boolean component7() {
        return getSetOption();
    }

    @Override
    public Long value1() {
        return getOid();
    }

    @Override
    public Long value2() {
        return getRoleid();
    }

    @Override
    public Long value3() {
        return getMember();
    }

    @Override
    public Long value4() {
        return getGrantor();
    }

    @Override
    public Boolean value5() {
        return getAdminOption();
    }

    @Override
    public Boolean value6() {
        return getInheritOption();
    }

    @Override
    public Boolean value7() {
        return getSetOption();
    }

    @Override
    public PgAuthMembersRecord value1(Long value) {
        setOid(value);
        return this;
    }

    @Override
    public PgAuthMembersRecord value2(Long value) {
        setRoleid(value);
        return this;
    }

    @Override
    public PgAuthMembersRecord value3(Long value) {
        setMember(value);
        return this;
    }

    @Override
    public PgAuthMembersRecord value4(Long value) {
        setGrantor(value);
        return this;
    }

    @Override
    public PgAuthMembersRecord value5(Boolean value) {
        setAdminOption(value);
        return this;
    }

    @Override
    public PgAuthMembersRecord value6(Boolean value) {
        setInheritOption(value);
        return this;
    }

    @Override
    public PgAuthMembersRecord value7(Boolean value) {
        setSetOption(value);
        return this;
    }

    @Override
    public PgAuthMembersRecord values(Long value1, Long value2, Long value3, Long value4, Boolean value5, Boolean value6, Boolean value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgAuthMembersRecord
     */
    public PgAuthMembersRecord() {
        super(PgAuthMembers.PG_AUTH_MEMBERS);
    }

    /**
     * Create a detached, initialised PgAuthMembersRecord
     */
    public PgAuthMembersRecord(Long oid, Long roleid, Long member, Long grantor, Boolean adminOption, Boolean inheritOption, Boolean setOption) {
        super(PgAuthMembers.PG_AUTH_MEMBERS);

        setOid(oid);
        setRoleid(roleid);
        setMember(member);
        setGrantor(grantor);
        setAdminOption(adminOption);
        setInheritOption(inheritOption);
        setSetOption(setOption);
        resetChangedOnNotNull();
    }
}
