/*
 * This file is generated by jOOQ.
 */
package dev.ku01.shop.db.pg_catalog.tables.records;


import dev.ku01.shop.db.pg_catalog.tables.PgDatabase;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgDatabaseRecord extends UpdatableRecordImpl<PgDatabaseRecord> implements Record17<Long, String, Long, Integer, String, Boolean, Boolean, Integer, Long, Long, Long, String, String, String, String, String, String[]> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pg_catalog.pg_database.oid</code>.
     */
    public void setOid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_database.oid</code>.
     */
    public Long getOid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_database.datname</code>.
     */
    public void setDatname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_database.datname</code>.
     */
    public String getDatname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_database.datdba</code>.
     */
    public void setDatdba(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_database.datdba</code>.
     */
    public Long getDatdba() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_database.encoding</code>.
     */
    public void setEncoding(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_database.encoding</code>.
     */
    public Integer getEncoding() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_database.datlocprovider</code>.
     */
    public void setDatlocprovider(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_database.datlocprovider</code>.
     */
    public String getDatlocprovider() {
        return (String) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_database.datistemplate</code>.
     */
    public void setDatistemplate(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_database.datistemplate</code>.
     */
    public Boolean getDatistemplate() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>pg_catalog.pg_database.datallowconn</code>.
     */
    public void setDatallowconn(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_database.datallowconn</code>.
     */
    public Boolean getDatallowconn() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>pg_catalog.pg_database.datconnlimit</code>.
     */
    public void setDatconnlimit(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_database.datconnlimit</code>.
     */
    public Integer getDatconnlimit() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>pg_catalog.pg_database.datfrozenxid</code>.
     */
    public void setDatfrozenxid(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_database.datfrozenxid</code>.
     */
    public Long getDatfrozenxid() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>pg_catalog.pg_database.datminmxid</code>.
     */
    public void setDatminmxid(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_database.datminmxid</code>.
     */
    public Long getDatminmxid() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>pg_catalog.pg_database.dattablespace</code>.
     */
    public void setDattablespace(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_database.dattablespace</code>.
     */
    public Long getDattablespace() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>pg_catalog.pg_database.datcollate</code>.
     */
    public void setDatcollate(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_database.datcollate</code>.
     */
    public String getDatcollate() {
        return (String) get(11);
    }

    /**
     * Setter for <code>pg_catalog.pg_database.datctype</code>.
     */
    public void setDatctype(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_database.datctype</code>.
     */
    public String getDatctype() {
        return (String) get(12);
    }

    /**
     * Setter for <code>pg_catalog.pg_database.daticulocale</code>.
     */
    public void setDaticulocale(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_database.daticulocale</code>.
     */
    public String getDaticulocale() {
        return (String) get(13);
    }

    /**
     * Setter for <code>pg_catalog.pg_database.daticurules</code>.
     */
    public void setDaticurules(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_database.daticurules</code>.
     */
    public String getDaticurules() {
        return (String) get(14);
    }

    /**
     * Setter for <code>pg_catalog.pg_database.datcollversion</code>.
     */
    public void setDatcollversion(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_database.datcollversion</code>.
     */
    public String getDatcollversion() {
        return (String) get(15);
    }

    /**
     * Setter for <code>pg_catalog.pg_database.datacl</code>.
     */
    public void setDatacl(String[] value) {
        set(16, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_database.datacl</code>.
     */
    public String[] getDatacl() {
        return (String[]) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row17<Long, String, Long, Integer, String, Boolean, Boolean, Integer, Long, Long, Long, String, String, String, String, String, String[]> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    @Override
    public Row17<Long, String, Long, Integer, String, Boolean, Boolean, Integer, Long, Long, Long, String, String, String, String, String, String[]> valuesRow() {
        return (Row17) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return PgDatabase.PG_DATABASE.OID;
    }

    @Override
    public Field<String> field2() {
        return PgDatabase.PG_DATABASE.DATNAME;
    }

    @Override
    public Field<Long> field3() {
        return PgDatabase.PG_DATABASE.DATDBA;
    }

    @Override
    public Field<Integer> field4() {
        return PgDatabase.PG_DATABASE.ENCODING;
    }

    @Override
    public Field<String> field5() {
        return PgDatabase.PG_DATABASE.DATLOCPROVIDER;
    }

    @Override
    public Field<Boolean> field6() {
        return PgDatabase.PG_DATABASE.DATISTEMPLATE;
    }

    @Override
    public Field<Boolean> field7() {
        return PgDatabase.PG_DATABASE.DATALLOWCONN;
    }

    @Override
    public Field<Integer> field8() {
        return PgDatabase.PG_DATABASE.DATCONNLIMIT;
    }

    @Override
    public Field<Long> field9() {
        return PgDatabase.PG_DATABASE.DATFROZENXID;
    }

    @Override
    public Field<Long> field10() {
        return PgDatabase.PG_DATABASE.DATMINMXID;
    }

    @Override
    public Field<Long> field11() {
        return PgDatabase.PG_DATABASE.DATTABLESPACE;
    }

    @Override
    public Field<String> field12() {
        return PgDatabase.PG_DATABASE.DATCOLLATE;
    }

    @Override
    public Field<String> field13() {
        return PgDatabase.PG_DATABASE.DATCTYPE;
    }

    @Override
    public Field<String> field14() {
        return PgDatabase.PG_DATABASE.DATICULOCALE;
    }

    @Override
    public Field<String> field15() {
        return PgDatabase.PG_DATABASE.DATICURULES;
    }

    @Override
    public Field<String> field16() {
        return PgDatabase.PG_DATABASE.DATCOLLVERSION;
    }

    @Override
    public Field<String[]> field17() {
        return PgDatabase.PG_DATABASE.DATACL;
    }

    @Override
    public Long component1() {
        return getOid();
    }

    @Override
    public String component2() {
        return getDatname();
    }

    @Override
    public Long component3() {
        return getDatdba();
    }

    @Override
    public Integer component4() {
        return getEncoding();
    }

    @Override
    public String component5() {
        return getDatlocprovider();
    }

    @Override
    public Boolean component6() {
        return getDatistemplate();
    }

    @Override
    public Boolean component7() {
        return getDatallowconn();
    }

    @Override
    public Integer component8() {
        return getDatconnlimit();
    }

    @Override
    public Long component9() {
        return getDatfrozenxid();
    }

    @Override
    public Long component10() {
        return getDatminmxid();
    }

    @Override
    public Long component11() {
        return getDattablespace();
    }

    @Override
    public String component12() {
        return getDatcollate();
    }

    @Override
    public String component13() {
        return getDatctype();
    }

    @Override
    public String component14() {
        return getDaticulocale();
    }

    @Override
    public String component15() {
        return getDaticurules();
    }

    @Override
    public String component16() {
        return getDatcollversion();
    }

    @Override
    public String[] component17() {
        return getDatacl();
    }

    @Override
    public Long value1() {
        return getOid();
    }

    @Override
    public String value2() {
        return getDatname();
    }

    @Override
    public Long value3() {
        return getDatdba();
    }

    @Override
    public Integer value4() {
        return getEncoding();
    }

    @Override
    public String value5() {
        return getDatlocprovider();
    }

    @Override
    public Boolean value6() {
        return getDatistemplate();
    }

    @Override
    public Boolean value7() {
        return getDatallowconn();
    }

    @Override
    public Integer value8() {
        return getDatconnlimit();
    }

    @Override
    public Long value9() {
        return getDatfrozenxid();
    }

    @Override
    public Long value10() {
        return getDatminmxid();
    }

    @Override
    public Long value11() {
        return getDattablespace();
    }

    @Override
    public String value12() {
        return getDatcollate();
    }

    @Override
    public String value13() {
        return getDatctype();
    }

    @Override
    public String value14() {
        return getDaticulocale();
    }

    @Override
    public String value15() {
        return getDaticurules();
    }

    @Override
    public String value16() {
        return getDatcollversion();
    }

    @Override
    public String[] value17() {
        return getDatacl();
    }

    @Override
    public PgDatabaseRecord value1(Long value) {
        setOid(value);
        return this;
    }

    @Override
    public PgDatabaseRecord value2(String value) {
        setDatname(value);
        return this;
    }

    @Override
    public PgDatabaseRecord value3(Long value) {
        setDatdba(value);
        return this;
    }

    @Override
    public PgDatabaseRecord value4(Integer value) {
        setEncoding(value);
        return this;
    }

    @Override
    public PgDatabaseRecord value5(String value) {
        setDatlocprovider(value);
        return this;
    }

    @Override
    public PgDatabaseRecord value6(Boolean value) {
        setDatistemplate(value);
        return this;
    }

    @Override
    public PgDatabaseRecord value7(Boolean value) {
        setDatallowconn(value);
        return this;
    }

    @Override
    public PgDatabaseRecord value8(Integer value) {
        setDatconnlimit(value);
        return this;
    }

    @Override
    public PgDatabaseRecord value9(Long value) {
        setDatfrozenxid(value);
        return this;
    }

    @Override
    public PgDatabaseRecord value10(Long value) {
        setDatminmxid(value);
        return this;
    }

    @Override
    public PgDatabaseRecord value11(Long value) {
        setDattablespace(value);
        return this;
    }

    @Override
    public PgDatabaseRecord value12(String value) {
        setDatcollate(value);
        return this;
    }

    @Override
    public PgDatabaseRecord value13(String value) {
        setDatctype(value);
        return this;
    }

    @Override
    public PgDatabaseRecord value14(String value) {
        setDaticulocale(value);
        return this;
    }

    @Override
    public PgDatabaseRecord value15(String value) {
        setDaticurules(value);
        return this;
    }

    @Override
    public PgDatabaseRecord value16(String value) {
        setDatcollversion(value);
        return this;
    }

    @Override
    public PgDatabaseRecord value17(String[] value) {
        setDatacl(value);
        return this;
    }

    @Override
    public PgDatabaseRecord values(Long value1, String value2, Long value3, Integer value4, String value5, Boolean value6, Boolean value7, Integer value8, Long value9, Long value10, Long value11, String value12, String value13, String value14, String value15, String value16, String[] value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgDatabaseRecord
     */
    public PgDatabaseRecord() {
        super(PgDatabase.PG_DATABASE);
    }

    /**
     * Create a detached, initialised PgDatabaseRecord
     */
    public PgDatabaseRecord(Long oid, String datname, Long datdba, Integer encoding, String datlocprovider, Boolean datistemplate, Boolean datallowconn, Integer datconnlimit, Long datfrozenxid, Long datminmxid, Long dattablespace, String datcollate, String datctype, String daticulocale, String daticurules, String datcollversion, String[] datacl) {
        super(PgDatabase.PG_DATABASE);

        setOid(oid);
        setDatname(datname);
        setDatdba(datdba);
        setEncoding(encoding);
        setDatlocprovider(datlocprovider);
        setDatistemplate(datistemplate);
        setDatallowconn(datallowconn);
        setDatconnlimit(datconnlimit);
        setDatfrozenxid(datfrozenxid);
        setDatminmxid(datminmxid);
        setDattablespace(dattablespace);
        setDatcollate(datcollate);
        setDatctype(datctype);
        setDaticulocale(daticulocale);
        setDaticurules(daticurules);
        setDatcollversion(datcollversion);
        setDatacl(datacl);
        resetChangedOnNotNull();
    }
}
