/*
 * This file is generated by jOOQ.
 */
package dev.ku01.shop.db.pg_catalog.tables.records;


import dev.ku01.shop.db.pg_catalog.tables.PgGetPublicationTables;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgGetPublicationTablesRecord extends TableRecordImpl<PgGetPublicationTablesRecord> implements Record4<Long, Long, Object[], Object> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pg_catalog.pg_get_publication_tables.pubid</code>.
     */
    public void setPubid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_get_publication_tables.pubid</code>.
     */
    public Long getPubid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_get_publication_tables.relid</code>.
     */
    public void setRelid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_get_publication_tables.relid</code>.
     */
    public Long getRelid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_get_publication_tables.attrs</code>.
     */
    public void setAttrs(Object[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_get_publication_tables.attrs</code>.
     */
    public Object[] getAttrs() {
        return (Object[]) get(2);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setQual(Object value) {
        set(3, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getQual() {
        return get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, Object[], Object> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, Object[], Object> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return PgGetPublicationTables.PG_GET_PUBLICATION_TABLES.PUBID;
    }

    @Override
    public Field<Long> field2() {
        return PgGetPublicationTables.PG_GET_PUBLICATION_TABLES.RELID;
    }

    @Override
    public Field<Object[]> field3() {
        return PgGetPublicationTables.PG_GET_PUBLICATION_TABLES.ATTRS;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Field<Object> field4() {
        return PgGetPublicationTables.PG_GET_PUBLICATION_TABLES.QUAL;
    }

    @Override
    public Long component1() {
        return getPubid();
    }

    @Override
    public Long component2() {
        return getRelid();
    }

    @Override
    public Object[] component3() {
        return getAttrs();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Object component4() {
        return getQual();
    }

    @Override
    public Long value1() {
        return getPubid();
    }

    @Override
    public Long value2() {
        return getRelid();
    }

    @Override
    public Object[] value3() {
        return getAttrs();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Object value4() {
        return getQual();
    }

    @Override
    public PgGetPublicationTablesRecord value1(Long value) {
        setPubid(value);
        return this;
    }

    @Override
    public PgGetPublicationTablesRecord value2(Long value) {
        setRelid(value);
        return this;
    }

    @Override
    public PgGetPublicationTablesRecord value3(Object[] value) {
        setAttrs(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public PgGetPublicationTablesRecord value4(Object value) {
        setQual(value);
        return this;
    }

    @Override
    public PgGetPublicationTablesRecord values(Long value1, Long value2, Object[] value3, Object value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgGetPublicationTablesRecord
     */
    public PgGetPublicationTablesRecord() {
        super(PgGetPublicationTables.PG_GET_PUBLICATION_TABLES);
    }

    /**
     * Create a detached, initialised PgGetPublicationTablesRecord
     */
    public PgGetPublicationTablesRecord(Long pubid, Long relid, Object[] attrs, Object qual) {
        super(PgGetPublicationTables.PG_GET_PUBLICATION_TABLES);

        setPubid(pubid);
        setRelid(relid);
        setAttrs(attrs);
        setQual(qual);
        resetChangedOnNotNull();
    }
}
