/*
 * This file is generated by jOOQ.
 */
package dev.ku01.shop.db.pg_catalog.tables.records;


import dev.ku01.shop.db.pg_catalog.tables.PgPreparedStatements;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgPreparedStatementsRecord extends TableRecordImpl<PgPreparedStatementsRecord> implements Record8<String, String, OffsetDateTime, Object[], Object[], Boolean, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pg_catalog.pg_prepared_statements.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_prepared_statements.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_prepared_statements.statement</code>.
     */
    public void setStatement(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_prepared_statements.statement</code>.
     */
    public String getStatement() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_prepared_statements.prepare_time</code>.
     */
    public void setPrepareTime(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_prepared_statements.prepare_time</code>.
     */
    public OffsetDateTime getPrepareTime() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_prepared_statements.parameter_types</code>.
     */
    public void setParameterTypes(Object[] value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_prepared_statements.parameter_types</code>.
     */
    public Object[] getParameterTypes() {
        return (Object[]) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_prepared_statements.result_types</code>.
     */
    public void setResultTypes(Object[] value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_prepared_statements.result_types</code>.
     */
    public Object[] getResultTypes() {
        return (Object[]) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_prepared_statements.from_sql</code>.
     */
    public void setFromSql(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_prepared_statements.from_sql</code>.
     */
    public Boolean getFromSql() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>pg_catalog.pg_prepared_statements.generic_plans</code>.
     */
    public void setGenericPlans(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_prepared_statements.generic_plans</code>.
     */
    public Long getGenericPlans() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>pg_catalog.pg_prepared_statements.custom_plans</code>.
     */
    public void setCustomPlans(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_prepared_statements.custom_plans</code>.
     */
    public Long getCustomPlans() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<String, String, OffsetDateTime, Object[], Object[], Boolean, Long, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<String, String, OffsetDateTime, Object[], Object[], Boolean, Long, Long> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return PgPreparedStatements.PG_PREPARED_STATEMENTS.NAME;
    }

    @Override
    public Field<String> field2() {
        return PgPreparedStatements.PG_PREPARED_STATEMENTS.STATEMENT;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return PgPreparedStatements.PG_PREPARED_STATEMENTS.PREPARE_TIME;
    }

    @Override
    public Field<Object[]> field4() {
        return PgPreparedStatements.PG_PREPARED_STATEMENTS.PARAMETER_TYPES;
    }

    @Override
    public Field<Object[]> field5() {
        return PgPreparedStatements.PG_PREPARED_STATEMENTS.RESULT_TYPES;
    }

    @Override
    public Field<Boolean> field6() {
        return PgPreparedStatements.PG_PREPARED_STATEMENTS.FROM_SQL;
    }

    @Override
    public Field<Long> field7() {
        return PgPreparedStatements.PG_PREPARED_STATEMENTS.GENERIC_PLANS;
    }

    @Override
    public Field<Long> field8() {
        return PgPreparedStatements.PG_PREPARED_STATEMENTS.CUSTOM_PLANS;
    }

    @Override
    public String component1() {
        return getName();
    }

    @Override
    public String component2() {
        return getStatement();
    }

    @Override
    public OffsetDateTime component3() {
        return getPrepareTime();
    }

    @Override
    public Object[] component4() {
        return getParameterTypes();
    }

    @Override
    public Object[] component5() {
        return getResultTypes();
    }

    @Override
    public Boolean component6() {
        return getFromSql();
    }

    @Override
    public Long component7() {
        return getGenericPlans();
    }

    @Override
    public Long component8() {
        return getCustomPlans();
    }

    @Override
    public String value1() {
        return getName();
    }

    @Override
    public String value2() {
        return getStatement();
    }

    @Override
    public OffsetDateTime value3() {
        return getPrepareTime();
    }

    @Override
    public Object[] value4() {
        return getParameterTypes();
    }

    @Override
    public Object[] value5() {
        return getResultTypes();
    }

    @Override
    public Boolean value6() {
        return getFromSql();
    }

    @Override
    public Long value7() {
        return getGenericPlans();
    }

    @Override
    public Long value8() {
        return getCustomPlans();
    }

    @Override
    public PgPreparedStatementsRecord value1(String value) {
        setName(value);
        return this;
    }

    @Override
    public PgPreparedStatementsRecord value2(String value) {
        setStatement(value);
        return this;
    }

    @Override
    public PgPreparedStatementsRecord value3(OffsetDateTime value) {
        setPrepareTime(value);
        return this;
    }

    @Override
    public PgPreparedStatementsRecord value4(Object[] value) {
        setParameterTypes(value);
        return this;
    }

    @Override
    public PgPreparedStatementsRecord value5(Object[] value) {
        setResultTypes(value);
        return this;
    }

    @Override
    public PgPreparedStatementsRecord value6(Boolean value) {
        setFromSql(value);
        return this;
    }

    @Override
    public PgPreparedStatementsRecord value7(Long value) {
        setGenericPlans(value);
        return this;
    }

    @Override
    public PgPreparedStatementsRecord value8(Long value) {
        setCustomPlans(value);
        return this;
    }

    @Override
    public PgPreparedStatementsRecord values(String value1, String value2, OffsetDateTime value3, Object[] value4, Object[] value5, Boolean value6, Long value7, Long value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgPreparedStatementsRecord
     */
    public PgPreparedStatementsRecord() {
        super(PgPreparedStatements.PG_PREPARED_STATEMENTS);
    }

    /**
     * Create a detached, initialised PgPreparedStatementsRecord
     */
    public PgPreparedStatementsRecord(String name, String statement, OffsetDateTime prepareTime, Object[] parameterTypes, Object[] resultTypes, Boolean fromSql, Long genericPlans, Long customPlans) {
        super(PgPreparedStatements.PG_PREPARED_STATEMENTS);

        setName(name);
        setStatement(statement);
        setPrepareTime(prepareTime);
        setParameterTypes(parameterTypes);
        setResultTypes(resultTypes);
        setFromSql(fromSql);
        setGenericPlans(genericPlans);
        setCustomPlans(customPlans);
        resetChangedOnNotNull();
    }
}
