/*
 * This file is generated by jOOQ.
 */
package dev.ku01.shop.db.pg_catalog.tables.records;


import dev.ku01.shop.db.pg_catalog.tables.PgPublicationRel;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgPublicationRelRecord extends UpdatableRecordImpl<PgPublicationRelRecord> implements Record5<Long, Long, Long, Object, Object[]> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pg_catalog.pg_publication_rel.oid</code>.
     */
    public void setOid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_publication_rel.oid</code>.
     */
    public Long getOid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_publication_rel.prpubid</code>.
     */
    public void setPrpubid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_publication_rel.prpubid</code>.
     */
    public Long getPrpubid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_publication_rel.prrelid</code>.
     */
    public void setPrrelid(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_publication_rel.prrelid</code>.
     */
    public Long getPrrelid() {
        return (Long) get(2);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setPrqual(Object value) {
        set(3, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getPrqual() {
        return get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_publication_rel.prattrs</code>.
     */
    public void setPrattrs(Object[] value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_publication_rel.prattrs</code>.
     */
    public Object[] getPrattrs() {
        return (Object[]) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, Object, Object[]> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, Long, Object, Object[]> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return PgPublicationRel.PG_PUBLICATION_REL.OID;
    }

    @Override
    public Field<Long> field2() {
        return PgPublicationRel.PG_PUBLICATION_REL.PRPUBID;
    }

    @Override
    public Field<Long> field3() {
        return PgPublicationRel.PG_PUBLICATION_REL.PRRELID;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Field<Object> field4() {
        return PgPublicationRel.PG_PUBLICATION_REL.PRQUAL;
    }

    @Override
    public Field<Object[]> field5() {
        return PgPublicationRel.PG_PUBLICATION_REL.PRATTRS;
    }

    @Override
    public Long component1() {
        return getOid();
    }

    @Override
    public Long component2() {
        return getPrpubid();
    }

    @Override
    public Long component3() {
        return getPrrelid();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Object component4() {
        return getPrqual();
    }

    @Override
    public Object[] component5() {
        return getPrattrs();
    }

    @Override
    public Long value1() {
        return getOid();
    }

    @Override
    public Long value2() {
        return getPrpubid();
    }

    @Override
    public Long value3() {
        return getPrrelid();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Object value4() {
        return getPrqual();
    }

    @Override
    public Object[] value5() {
        return getPrattrs();
    }

    @Override
    public PgPublicationRelRecord value1(Long value) {
        setOid(value);
        return this;
    }

    @Override
    public PgPublicationRelRecord value2(Long value) {
        setPrpubid(value);
        return this;
    }

    @Override
    public PgPublicationRelRecord value3(Long value) {
        setPrrelid(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public PgPublicationRelRecord value4(Object value) {
        setPrqual(value);
        return this;
    }

    @Override
    public PgPublicationRelRecord value5(Object[] value) {
        setPrattrs(value);
        return this;
    }

    @Override
    public PgPublicationRelRecord values(Long value1, Long value2, Long value3, Object value4, Object[] value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgPublicationRelRecord
     */
    public PgPublicationRelRecord() {
        super(PgPublicationRel.PG_PUBLICATION_REL);
    }

    /**
     * Create a detached, initialised PgPublicationRelRecord
     */
    public PgPublicationRelRecord(Long oid, Long prpubid, Long prrelid, Object prqual, Object[] prattrs) {
        super(PgPublicationRel.PG_PUBLICATION_REL);

        setOid(oid);
        setPrpubid(prpubid);
        setPrrelid(prrelid);
        setPrqual(prqual);
        setPrattrs(prattrs);
        resetChangedOnNotNull();
    }
}
