/*
 * This file is generated by jOOQ.
 */
package dev.ku01.shop.db.pg_catalog.tables.records;


import dev.ku01.shop.db.pg_catalog.tables.PgStatGssapi;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatGssapiRecord extends TableRecordImpl<PgStatGssapiRecord> implements Record5<Integer, Boolean, String, Boolean, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pg_catalog.pg_stat_gssapi.pid</code>.
     */
    public void setPid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_gssapi.pid</code>.
     */
    public Integer getPid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_gssapi.gss_authenticated</code>.
     */
    public void setGssAuthenticated(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_gssapi.gss_authenticated</code>.
     */
    public Boolean getGssAuthenticated() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_gssapi.principal</code>.
     */
    public void setPrincipal(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_gssapi.principal</code>.
     */
    public String getPrincipal() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_gssapi.encrypted</code>.
     */
    public void setEncrypted(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_gssapi.encrypted</code>.
     */
    public Boolean getEncrypted() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_gssapi.credentials_delegated</code>.
     */
    public void setCredentialsDelegated(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_gssapi.credentials_delegated</code>.
     */
    public Boolean getCredentialsDelegated() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Boolean, String, Boolean, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Boolean, String, Boolean, Boolean> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PgStatGssapi.PG_STAT_GSSAPI.PID;
    }

    @Override
    public Field<Boolean> field2() {
        return PgStatGssapi.PG_STAT_GSSAPI.GSS_AUTHENTICATED;
    }

    @Override
    public Field<String> field3() {
        return PgStatGssapi.PG_STAT_GSSAPI.PRINCIPAL;
    }

    @Override
    public Field<Boolean> field4() {
        return PgStatGssapi.PG_STAT_GSSAPI.ENCRYPTED;
    }

    @Override
    public Field<Boolean> field5() {
        return PgStatGssapi.PG_STAT_GSSAPI.CREDENTIALS_DELEGATED;
    }

    @Override
    public Integer component1() {
        return getPid();
    }

    @Override
    public Boolean component2() {
        return getGssAuthenticated();
    }

    @Override
    public String component3() {
        return getPrincipal();
    }

    @Override
    public Boolean component4() {
        return getEncrypted();
    }

    @Override
    public Boolean component5() {
        return getCredentialsDelegated();
    }

    @Override
    public Integer value1() {
        return getPid();
    }

    @Override
    public Boolean value2() {
        return getGssAuthenticated();
    }

    @Override
    public String value3() {
        return getPrincipal();
    }

    @Override
    public Boolean value4() {
        return getEncrypted();
    }

    @Override
    public Boolean value5() {
        return getCredentialsDelegated();
    }

    @Override
    public PgStatGssapiRecord value1(Integer value) {
        setPid(value);
        return this;
    }

    @Override
    public PgStatGssapiRecord value2(Boolean value) {
        setGssAuthenticated(value);
        return this;
    }

    @Override
    public PgStatGssapiRecord value3(String value) {
        setPrincipal(value);
        return this;
    }

    @Override
    public PgStatGssapiRecord value4(Boolean value) {
        setEncrypted(value);
        return this;
    }

    @Override
    public PgStatGssapiRecord value5(Boolean value) {
        setCredentialsDelegated(value);
        return this;
    }

    @Override
    public PgStatGssapiRecord values(Integer value1, Boolean value2, String value3, Boolean value4, Boolean value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgStatGssapiRecord
     */
    public PgStatGssapiRecord() {
        super(PgStatGssapi.PG_STAT_GSSAPI);
    }

    /**
     * Create a detached, initialised PgStatGssapiRecord
     */
    public PgStatGssapiRecord(Integer pid, Boolean gssAuthenticated, String principal, Boolean encrypted, Boolean credentialsDelegated) {
        super(PgStatGssapi.PG_STAT_GSSAPI);

        setPid(pid);
        setGssAuthenticated(gssAuthenticated);
        setPrincipal(principal);
        setEncrypted(encrypted);
        setCredentialsDelegated(credentialsDelegated);
        resetChangedOnNotNull();
    }
}
