/*
 * This file is generated by jOOQ.
 */
package dev.ku01.shop.db.pg_catalog.tables.records;


import dev.ku01.shop.db.pg_catalog.tables.PgStatisticExtData;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatisticExtDataRecord extends UpdatableRecordImpl<PgStatisticExtDataRecord> implements Record6<Long, Boolean, Object, Object, Object, PgStatisticRecord[]> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pg_catalog.pg_statistic_ext_data.stxoid</code>.
     */
    public void setStxoid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_statistic_ext_data.stxoid</code>.
     */
    public Long getStxoid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_statistic_ext_data.stxdinherit</code>.
     */
    public void setStxdinherit(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_statistic_ext_data.stxdinherit</code>.
     */
    public Boolean getStxdinherit() {
        return (Boolean) get(1);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setStxdndistinct(Object value) {
        set(2, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getStxdndistinct() {
        return get(2);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setStxddependencies(Object value) {
        set(3, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getStxddependencies() {
        return get(3);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setStxdmcv(Object value) {
        set(4, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getStxdmcv() {
        return get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_statistic_ext_data.stxdexpr</code>.
     */
    public void setStxdexpr(PgStatisticRecord[] value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_statistic_ext_data.stxdexpr</code>.
     */
    public PgStatisticRecord[] getStxdexpr() {
        return (PgStatisticRecord[]) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Boolean> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Boolean, Object, Object, Object, PgStatisticRecord[]> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Boolean, Object, Object, Object, PgStatisticRecord[]> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return PgStatisticExtData.PG_STATISTIC_EXT_DATA.STXOID;
    }

    @Override
    public Field<Boolean> field2() {
        return PgStatisticExtData.PG_STATISTIC_EXT_DATA.STXDINHERIT;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Field<Object> field3() {
        return PgStatisticExtData.PG_STATISTIC_EXT_DATA.STXDNDISTINCT;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Field<Object> field4() {
        return PgStatisticExtData.PG_STATISTIC_EXT_DATA.STXDDEPENDENCIES;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Field<Object> field5() {
        return PgStatisticExtData.PG_STATISTIC_EXT_DATA.STXDMCV;
    }

    @Override
    public Field<PgStatisticRecord[]> field6() {
        return PgStatisticExtData.PG_STATISTIC_EXT_DATA.STXDEXPR;
    }

    @Override
    public Long component1() {
        return getStxoid();
    }

    @Override
    public Boolean component2() {
        return getStxdinherit();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Object component3() {
        return getStxdndistinct();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Object component4() {
        return getStxddependencies();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Object component5() {
        return getStxdmcv();
    }

    @Override
    public PgStatisticRecord[] component6() {
        return getStxdexpr();
    }

    @Override
    public Long value1() {
        return getStxoid();
    }

    @Override
    public Boolean value2() {
        return getStxdinherit();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Object value3() {
        return getStxdndistinct();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Object value4() {
        return getStxddependencies();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Object value5() {
        return getStxdmcv();
    }

    @Override
    public PgStatisticRecord[] value6() {
        return getStxdexpr();
    }

    @Override
    public PgStatisticExtDataRecord value1(Long value) {
        setStxoid(value);
        return this;
    }

    @Override
    public PgStatisticExtDataRecord value2(Boolean value) {
        setStxdinherit(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public PgStatisticExtDataRecord value3(Object value) {
        setStxdndistinct(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public PgStatisticExtDataRecord value4(Object value) {
        setStxddependencies(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public PgStatisticExtDataRecord value5(Object value) {
        setStxdmcv(value);
        return this;
    }

    @Override
    public PgStatisticExtDataRecord value6(PgStatisticRecord[] value) {
        setStxdexpr(value);
        return this;
    }

    @Override
    public PgStatisticExtDataRecord values(Long value1, Boolean value2, Object value3, Object value4, Object value5, PgStatisticRecord[] value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgStatisticExtDataRecord
     */
    public PgStatisticExtDataRecord() {
        super(PgStatisticExtData.PG_STATISTIC_EXT_DATA);
    }

    /**
     * Create a detached, initialised PgStatisticExtDataRecord
     */
    public PgStatisticExtDataRecord(Long stxoid, Boolean stxdinherit, Object stxdndistinct, Object stxddependencies, Object stxdmcv, PgStatisticRecord[] stxdexpr) {
        super(PgStatisticExtData.PG_STATISTIC_EXT_DATA);

        setStxoid(stxoid);
        setStxdinherit(stxdinherit);
        setStxdndistinct(stxdndistinct);
        setStxddependencies(stxddependencies);
        setStxdmcv(stxdmcv);
        setStxdexpr(stxdexpr);
        resetChangedOnNotNull();
    }
}
