/*
 * This file is generated by jOOQ.
 */
package dev.ku01.shop.db.pg_catalog.tables.records;


import dev.ku01.shop.db.pg_catalog.tables.PgStatSubscription;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatSubscriptionRecord extends TableRecordImpl<PgStatSubscriptionRecord> implements Record10<Long, String, Integer, Integer, Long, Object, OffsetDateTime, OffsetDateTime, Object, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pg_catalog.pg_stat_subscription.subid</code>.
     */
    public void setSubid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_subscription.subid</code>.
     */
    public Long getSubid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_subscription.subname</code>.
     */
    public void setSubname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_subscription.subname</code>.
     */
    public String getSubname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_subscription.pid</code>.
     */
    public void setPid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_subscription.pid</code>.
     */
    public Integer getPid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_subscription.leader_pid</code>.
     */
    public void setLeaderPid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_subscription.leader_pid</code>.
     */
    public Integer getLeaderPid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_subscription.relid</code>.
     */
    public void setRelid(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_subscription.relid</code>.
     */
    public Long getRelid() {
        return (Long) get(4);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setReceivedLsn(Object value) {
        set(5, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getReceivedLsn() {
        return get(5);
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_stat_subscription.last_msg_send_time</code>.
     */
    public void setLastMsgSendTime(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_stat_subscription.last_msg_send_time</code>.
     */
    public OffsetDateTime getLastMsgSendTime() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for
     * <code>pg_catalog.pg_stat_subscription.last_msg_receipt_time</code>.
     */
    public void setLastMsgReceiptTime(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>pg_catalog.pg_stat_subscription.last_msg_receipt_time</code>.
     */
    public OffsetDateTime getLastMsgReceiptTime() {
        return (OffsetDateTime) get(7);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setLatestEndLsn(Object value) {
        set(8, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getLatestEndLsn() {
        return get(8);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_subscription.latest_end_time</code>.
     */
    public void setLatestEndTime(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_subscription.latest_end_time</code>.
     */
    public OffsetDateTime getLatestEndTime() {
        return (OffsetDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, Integer, Integer, Long, Object, OffsetDateTime, OffsetDateTime, Object, OffsetDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, String, Integer, Integer, Long, Object, OffsetDateTime, OffsetDateTime, Object, OffsetDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return PgStatSubscription.PG_STAT_SUBSCRIPTION.SUBID;
    }

    @Override
    public Field<String> field2() {
        return PgStatSubscription.PG_STAT_SUBSCRIPTION.SUBNAME;
    }

    @Override
    public Field<Integer> field3() {
        return PgStatSubscription.PG_STAT_SUBSCRIPTION.PID;
    }

    @Override
    public Field<Integer> field4() {
        return PgStatSubscription.PG_STAT_SUBSCRIPTION.LEADER_PID;
    }

    @Override
    public Field<Long> field5() {
        return PgStatSubscription.PG_STAT_SUBSCRIPTION.RELID;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Field<Object> field6() {
        return PgStatSubscription.PG_STAT_SUBSCRIPTION.RECEIVED_LSN;
    }

    @Override
    public Field<OffsetDateTime> field7() {
        return PgStatSubscription.PG_STAT_SUBSCRIPTION.LAST_MSG_SEND_TIME;
    }

    @Override
    public Field<OffsetDateTime> field8() {
        return PgStatSubscription.PG_STAT_SUBSCRIPTION.LAST_MSG_RECEIPT_TIME;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Field<Object> field9() {
        return PgStatSubscription.PG_STAT_SUBSCRIPTION.LATEST_END_LSN;
    }

    @Override
    public Field<OffsetDateTime> field10() {
        return PgStatSubscription.PG_STAT_SUBSCRIPTION.LATEST_END_TIME;
    }

    @Override
    public Long component1() {
        return getSubid();
    }

    @Override
    public String component2() {
        return getSubname();
    }

    @Override
    public Integer component3() {
        return getPid();
    }

    @Override
    public Integer component4() {
        return getLeaderPid();
    }

    @Override
    public Long component5() {
        return getRelid();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Object component6() {
        return getReceivedLsn();
    }

    @Override
    public OffsetDateTime component7() {
        return getLastMsgSendTime();
    }

    @Override
    public OffsetDateTime component8() {
        return getLastMsgReceiptTime();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Object component9() {
        return getLatestEndLsn();
    }

    @Override
    public OffsetDateTime component10() {
        return getLatestEndTime();
    }

    @Override
    public Long value1() {
        return getSubid();
    }

    @Override
    public String value2() {
        return getSubname();
    }

    @Override
    public Integer value3() {
        return getPid();
    }

    @Override
    public Integer value4() {
        return getLeaderPid();
    }

    @Override
    public Long value5() {
        return getRelid();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Object value6() {
        return getReceivedLsn();
    }

    @Override
    public OffsetDateTime value7() {
        return getLastMsgSendTime();
    }

    @Override
    public OffsetDateTime value8() {
        return getLastMsgReceiptTime();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Object value9() {
        return getLatestEndLsn();
    }

    @Override
    public OffsetDateTime value10() {
        return getLatestEndTime();
    }

    @Override
    public PgStatSubscriptionRecord value1(Long value) {
        setSubid(value);
        return this;
    }

    @Override
    public PgStatSubscriptionRecord value2(String value) {
        setSubname(value);
        return this;
    }

    @Override
    public PgStatSubscriptionRecord value3(Integer value) {
        setPid(value);
        return this;
    }

    @Override
    public PgStatSubscriptionRecord value4(Integer value) {
        setLeaderPid(value);
        return this;
    }

    @Override
    public PgStatSubscriptionRecord value5(Long value) {
        setRelid(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public PgStatSubscriptionRecord value6(Object value) {
        setReceivedLsn(value);
        return this;
    }

    @Override
    public PgStatSubscriptionRecord value7(OffsetDateTime value) {
        setLastMsgSendTime(value);
        return this;
    }

    @Override
    public PgStatSubscriptionRecord value8(OffsetDateTime value) {
        setLastMsgReceiptTime(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public PgStatSubscriptionRecord value9(Object value) {
        setLatestEndLsn(value);
        return this;
    }

    @Override
    public PgStatSubscriptionRecord value10(OffsetDateTime value) {
        setLatestEndTime(value);
        return this;
    }

    @Override
    public PgStatSubscriptionRecord values(Long value1, String value2, Integer value3, Integer value4, Long value5, Object value6, OffsetDateTime value7, OffsetDateTime value8, Object value9, OffsetDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgStatSubscriptionRecord
     */
    public PgStatSubscriptionRecord() {
        super(PgStatSubscription.PG_STAT_SUBSCRIPTION);
    }

    /**
     * Create a detached, initialised PgStatSubscriptionRecord
     */
    public PgStatSubscriptionRecord(Long subid, String subname, Integer pid, Integer leaderPid, Long relid, Object receivedLsn, OffsetDateTime lastMsgSendTime, OffsetDateTime lastMsgReceiptTime, Object latestEndLsn, OffsetDateTime latestEndTime) {
        super(PgStatSubscription.PG_STAT_SUBSCRIPTION);

        setSubid(subid);
        setSubname(subname);
        setPid(pid);
        setLeaderPid(leaderPid);
        setRelid(relid);
        setReceivedLsn(receivedLsn);
        setLastMsgSendTime(lastMsgSendTime);
        setLastMsgReceiptTime(lastMsgReceiptTime);
        setLatestEndLsn(latestEndLsn);
        setLatestEndTime(latestEndTime);
        resetChangedOnNotNull();
    }
}
